steps:
  - name: gcr.io/cloud-builders/gsutil
    args: # need to the link after creating the folder in GCP
      - cp
      - '-r'
      - 'gs://ftp-infra-us-01/UI/QTT/dev/masteradminui/build/bunny-publish.js'
      - 'gs://ftp-infra-us-01/UI/QTT/dev/masteradminui/build/pre-build.js'
      - 'gs://ftp-infra-us-01/UI/QTT/dev/masteradminui/src/environment.dev.ts'
      - .
    id: Fetch GCS files
  - name: gcr.io/cloud-builders/git
    args:
      - '-c'
      - |
        mv /workspace/bunny-publish.js /workspace/build/
        mv /workspace/pre-build.js /workspace/build/
        mv /workspace/environment.dev.ts /workspace/src/environments/
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        docker pull $_IMG:latest || true
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >
        date -u +%Y%m%dT%H%M > /workspace/TAG.txt &&  docker build
        --cache-from=$_IMG:latest -t $_IMG:$SHORT_SHA -t $_IMG:latest -t
        $_IMG:qtt-dev-$(cat /workspace/TAG.txt) . &&  docker push --all-tags
        $_IMG
    entrypoint: sh
# substitutions:
#   _IMG: >-
#     asia-south1-docker.pkg.dev/subtle-cubist-336614/ftp-artifact-asia-south/masteradmin
# tags:
#   - masteradmin
#   - dev
#   - qtt

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  TAG_NAME: latest











