steps:
  
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/demo-project:$TAG_NAME'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/demo-project:$TAG_NAME'

  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - ls -l /workspace
    entrypoint: bash
 
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - '-c'
      - |

        if [[ "$TAG_NAME" == *"malik"* ]]; then
          gsutil cp gs://malik-dev/index.html /workspace/index.html
        elif [[ "$TAG_NAME" == *"nawas"* ]]; then
          gsutil cp gs://nawas-dev/index.html /workspace/index.html
        fi
    entrypoint: bash
  - name: gcr.io/cloud-builders/curl
    args:
      - '-X'
      - POST
      - >-
        https://api.telegram.org/bot{token}/sendMessage
      - '-d'
      - chat_id=:{id}
      - '-d'
      - 'text=Build triggered for ${TAG_NAME}'
    id: Send Telegram Notification
options:
  substitutionOption: ALLOW_LOOSE
  logging: NONE

    if [[ "$TAG_NAME" =~ ^malik-(dev|prod)-v[0-9]+$ ]]; then
          echo "Matched malik environment tag: $TAG_NAME"
          gsutil cp gs://demo-react-bucket/malik/${BASH_REMATCH[1]}/index.html /workspace/index.html
        elif [[ "$TAG_NAME" =~ ^nawas-(dev|prod)-v[0-9]+$ ]]; then
          echo "Matched nawas environment tag: $TAG_NAME"
          gsutil cp gs://demo-react-bucket/nawas/${BASH_REMATCH[1]}/index.html /workspace/index.html
        else
          echo "No valid tag matched. Attempting to use default file."
          if gsutil -q stat gs://demo-react-bucket/default/index.html; then
            gsutil cp gs://demo-react-bucket/default/index.html /workspace/index.html
          else
            echo "Default file not found. Exiting gracefully."
            exit 0
          fi
        fi
    entrypoint: bash
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - ls -l /workspace
    entrypoint: bash
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/demo-project:$TAG_NAME'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/demo-project:$TAG_NAME'
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  TAG_NAME: latest












# steps:
#   # Step 1: Build the Docker image
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'malikakb/demo-project:$TAG_NAME', '.']

#   # Step 2: Push the Docker image to Docker Hub
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'malikakb/demo-project:$TAG_NAME']

#   # Step 3: Copy the correct index.html file from GCS based on the tag
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         if [[ "$TAG_NAME" == *"malik"* ]]; then
#           gsutil cp gs://demo-react-bucket/malik/dev/index.html /workspace/index.html
#         elif [[ "$TAG_NAME" == *"nawas"* ]]; then
#           gsutil cp gs://nawas-dev/index.html /workspace/index.html
#         fi

#   Step 4: Send a Telegram notification
#   - name: 'gcr.io/cloud-builders/curl'
#     args:
#       - '-X'
#       - 'POST'
#       - 'https://api.telegram.org/bot7335978148:AAE82z_6CcesA3S8-yGl_XSNic-g3IkMkgs/sendMessage'
#       - '-d'
#       - 'chat_id=-4663907958'
#       - '-d'
#       - 'text=Build triggered for $TAG_NAME'

#     steps:  
#       - name: 'gcr.io/cloud-builders/gcloud'
#         args: ['app', 'deploy']
#     options:
#         logging: CLOUD_LOGGING_ONLY
#         substitution_option: ALLOW_LOOSE  # Allow optional environment variables
#         machine_type: E2_SMALL  # (Optional) Cheaper machine if your build is lightweight

# steps:
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['pull', 'malikakb/demo-project:$TAG_NAME']
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         if [[ "$TAG_NAME" == *"malik"* ]]; then
#           gsutil cp gs://demo-react-bucket/malik/dev/index.html /workspace/index.html
#         elif [[ "$TAG_NAME" == *"nawas"* ]]; then
#           gsutil cp gs://nawas-dev/index.html /workspace/index.html
#         fi
     
# substitutions:
#   _TAG_NAME: latest
=======
>>>>>>> 825b802 (update cloudbuild.yaml)
